config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount ResqueWeb::Engine => '/resque_web'

  devise_for :administrators, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :subscribers, only: [:new, :create, :show]
  resources :inquiries, only: [:new, :create, :show]
  get '/unsubscribe/:token', to: 'users#unsubscribe',
                             as: :unsubscribe,
                             constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  get '/profile/edit', to: 'users#edit',
                       as: :edit_profile
  resources :users, only: [:show, :edit, :update, :index] do
    resources :bios, only: [:new, :index, :create]
  end
  resources :bios, only: [:show, :edit, :update, :index, :create, :new]
  resources :books, only: [:index, :show, :edit, :update, :new, :create] do
    resources :book_versions, path: 'versions', only: [:new, :create, :index]
    resources :campaigns, only: [:index, :new, :create]
    collection do
      get :browse
    end
  end
  resources :book_versions, only: [:edit, :update, :show]
  resources :images, only: :show
  resources :campaigns, only: [:show, :edit, :update, :destroy] do
    resources :contributions, only: [:new, :create]
    resources :rewards, only: [:index, :new, :create]
    member do
      get :terms
      patch :start
      patch :collect
      patch :cancel
      patch :prolong
    end
  end
  resources :contributions, only: [:edit, :update] do
    member do
      get :reward
      patch :set_reward
      get :payment
      patch :pay
    end
  end
  get '/contributions/:token', to: 'contributions#show',
                               as: :show_contribution,
                               constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  resources :payments, only: :create do
    collection do
      get :token
    end
  end
  resources :rewards, only: [:edit, :update, :destroy]
  resources :fulfillments, only: [:index] do
    member do
      patch :fulfill
    end
  end

  namespace :admin do
    resources :authors do
      resources :bios, only: [:new, :create]
      resources :books, only: [:index, :new, :create]
    end
    resources :bios, only: [:edit, :update]
    resources :books, only: [:edit, :destroy]
    resources :book_versions, only: :update
    resources :inquiries, only: [:index, :show] do
      member do
        patch :archive
      end
    end
    resources :users, only: [:index, :show]
    resources :bios, only: [:index, :show] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :book_versions, only: [:show, :index] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :campaigns, only: [:index, :show]
    resources :house_rewards
    resources :fulfillments, only: [:index] do
      member do
        patch :fulfill
      end
    end
    resources :payments, only: [:index, :show] do
      member do
        patch :refresh
        patch :refund
      end
    end
    resources :subscribers, only: [:index]
  end

  get 'pages/welcome'
  get 'pages/package_pricing'
  get 'pages/book_prices'
  get 'pages/a_la_carte_pricing'
  get 'pages/traditional_vs_pod'
  get 'pages/faqs'
  get 'pages/about_us'
  get 'pages/our_team'
  get 'pages/author_portal'
  get 'pages/why'
  get 'pages/community_standards'
  get 'pages/what_we_do'
  get 'pages/why_model_works'
  get 'pages/printing_costs'
  get 'pages/klososky'
  get 'pages/rewilding'
  get 'pages/discipling'
  get 'pages/predicament'
  get 'pages/covenant'
  get 'pages/piatt'

  get 'authors', to: 'bios#browse', as: :browse_authors
  get 'users', to: 'users#show', as: :user_root
  get 'admin', to: 'admin/users#index', as: :admin_root
  root to: 'pages#welcome'
end

app/models/house_reward.rb
# == Schema Information
#
# Table name: house_rewards
#
#  id                        :integer          not null, primary key
#  description               :string(255)      not null
#  physical_address_required :boolean          default(FALSE), not null
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  estimator_class           :string(200)
#  long_description          :text
#

class HouseReward < ActiveRecord::Base
  has_many :rewards

  validates :description, presence: true, length: { maximum: 255 }

  def estimator
    return nil unless @estimator || estimator_class.present?
    @estimator ||= estimator_class.constantize.new
  rescue NameError
    raise InvalidClassNameError.new "estimator_class \"#{estimator_class}\" is not a valid class."
  end

  def estimator=(estimator)
    if estimator.present? && !estimator.respond_to?(:estimate)
      raise ArgumentError.new("'estimator' must implement 'estimate'")
    end
    @estimator = estimator
  end

  def estimate_cost(count)
    return nil unless estimator
    estimator.estimate(count)
  end
end

class InvalidClassNameError < StandardError; end

app/controllers/admin/house_rewards_controller.rb
class Admin::HouseRewardsController < ApplicationController
  layout 'admin'

  before_filter :authenticate_administrator!
  before_filter :load_house_reward, only: [:edit, :update, :destroy, :show]

  respond_to :html

  def index
    @house_rewards = HouseReward.all.order(:description)
  end

  def new
    @house_reward = HouseReward.new
  end

  def create
    @house_reward = HouseReward.new house_reward_params
    flash[:notice] = 'The reward was created successfully.' if @house_reward.save
    respond_with @house_reward, location: admin_house_rewards_path
  end

  def edit
  end

  def update
    @house_reward.update_attributes house_reward_params
    flash[:notice] = 'The reward was updated successfully.' if @house_reward.save
    respond_with @house_reward, location: admin_house_rewards_path
  end

  def show
  end

  def destroy
    flash[:notice] = 'The reward was removed successfully.' if @house_reward.destroy
    respond_with @house_reward, location: admin_house_rewards_path
  end

  private

  def load_house_reward
    @house_reward = HouseReward.find(params[:id])
  end

  def house_reward_params
    params.require(:house_reward).permit(:description,
                                         :long_description,
                                         :physical_address_required,
                                         :estimator_class)
  end
end

app/helpers/admin/house_rewards_helper.rb
module Admin::HouseRewardsHelper
  def estimator_class_options_for_select(selected)
    options = [
      ['None', ''],
      ['Publishing', 'PublishingCostEstimator'],
      ['e-Book', 'EbookCostEstimator'],
    ]
    options_for_select(options, selected)
  end
end

app/views/admin/house_rewards/_form_fields.html.haml
.form-group{ :class => form_group_class(@house_reward, :description) }
  =f.label :description, class: 'control-label'
  =f.text_field :description, class: 'form-control', autofocus: true
  =help_blocks @house_reward, :description
.form-group{ :class => form_group_class(@house_reward, :long_description) }
  =f.label :long_description, 'Estimation method', class: 'control-label'
  =f.text_area :long_description, class: 'form-control'
  =help_blocks @house_reward, :long_description
.form-group{ :class => form_group_class(@house_reward, :estimator_class) }
  =f.label :estimator_class, 'Estimation method', class: 'control-label'
  =f.select :estimator_class, estimator_class_options_for_select(@house_reward.estimator_class), {}, class: 'form-control'
  =help_blocks @house_reward, :estimator_class
.checkbox
  %label
    =f.check_box :physical_address_required
    Physical address required
=f.submit 'Save', class: 'btn btn-primary', title: 'Click here to save the reward.'
=link_to 'Back', admin_house_rewards_path, class: 'btn btn-default', title: 'Click here to return to the list of house rewards.'

app/views/admin/house_rewards/edit.html.haml
=content_for :page_title do
  Edit house reward

.container.container-default
  .row
    .col-md-6
      =form_for([:admin, @house_reward]) do |f|
        =render 'form_fields', f: f

app/views/admin/house_rewards/index.html.haml
=content_for :page_title do
  Rewards

.container.container-default
  .row
    .col-md-6
      %table#rewards-table.table.table-striped
        %tr
          %th Description
          %th.text-center Address Req.?
          %th &nbsp;
        -@house_rewards.each do |house_reward|
          %tr
            %td= house_reward.description
            %td.text-center
              -if house_reward.physical_address_required?
                %span.glyphicon.glyphicon-check{ 'arial-hidden' => true }
              -else
                %span.glyphicon.glyphicon-unchecked{ 'arial-hidden' => true }
            %td
              .btn-group
                =link_to edit_admin_house_reward_path(house_reward), class: 'btn btn-info btn-xs edit-button', title: 'Click here to edit this reward.' do
                  %span.glyphicon.glyphicon-pencil{ 'arial-hidden' => true }
                =link_to admin_house_reward_path(house_reward), class: 'btn btn-danger btn-xs delete-button', title: 'Click here to edit this reward.', method: :delete, data: { confirm: 'Are you sure you want to delete this reward?' } do
                  %span.glyphicon.glyphicon-remove{ 'arial-hidden' => true }
      =link_to 'Add', new_admin_house_reward_path, class: 'btn btn-primary', title: 'Click here to add a new reward.'

app/views/admin/house_rewards/new.html.haml
=content_for :page_title do
  New house reward

.container.container-default
  .row
    .col-md-6
      =form_for([:admin, @house_reward]) do |f|
        =render 'form_fields', f: f

app/views/admin/house_rewards/show.html.haml
%h1 Admin::HouseRewards#show
%p Find me in app/views/admin/house_rewards/show.html.haml