config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount ResqueWeb::Engine => '/resque_web'

  devise_for :administrators, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :subscribers, only: [:new, :create, :show]
  resources :inquiries, only: [:new, :create, :show]
  get '/unsubscribe/:token', to: 'users#unsubscribe',
                             as: :unsubscribe,
                             constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  get '/profile/edit', to: 'users#edit',
                       as: :edit_profile
  resources :users, only: [:show, :edit, :update, :index] do
    resources :bios, only: [:new, :index, :create]
  end
  resources :bios, only: [:show, :edit, :update, :index, :create, :new]
  resources :books, only: [:index, :show, :edit, :update, :new, :create] do
    resources :book_versions, path: 'versions', only: [:new, :create, :index]
    resources :campaigns, only: [:index, :new, :create]
    collection do
      get :browse
    end
  end
  resources :book_versions, only: [:edit, :update, :show]
  resources :images, only: :show
  resources :campaigns, only: [:show, :edit, :update, :destroy] do
    resources :contributions, only: [:new, :create]
    resources :rewards, only: [:index, :new, :create]
    member do
      get :terms
      patch :start
      patch :collect
      patch :cancel
      patch :prolong
    end
  end
  resources :contributions, only: [:edit, :update] do
    member do
      get :reward
      patch :set_reward
      get :payment
      patch :pay
    end
  end
  get '/contributions/:token', to: 'contributions#show',
                               as: :show_contribution,
                               constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  resources :payments, only: :create do
    collection do
      get :token
    end
  end
  resources :rewards, only: [:edit, :update, :destroy]
  resources :fulfillments, only: [:index] do
    member do
      patch :fulfill
    end
  end

  namespace :admin do
    resources :authors do
      resources :bios, only: [:new, :create]
      resources :books, only: [:index, :new, :create]
    end
    resources :bios, only: [:edit, :update]
    resources :books, only: [:edit, :destroy]
    resources :book_versions, only: :update
    resources :inquiries, only: [:index, :show] do
      member do
        patch :archive
      end
    end
    resources :users, only: [:index, :show]
    resources :bios, only: [:index, :show] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :book_versions, only: [:show, :index] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :campaigns, only: [:index, :show]
    resources :house_rewards
    resources :fulfillments, only: [:index] do
      member do
        patch :fulfill
      end
    end
    resources :payments, only: [:index, :show] do
      member do
        patch :refresh
        patch :refund
      end
    end
    resources :subscribers, only: [:index]
  end

  get 'pages/welcome'
  get 'pages/package_pricing'
  get 'pages/book_prices'
  get 'pages/a_la_carte_pricing'
  get 'pages/traditional_vs_pod'
  get 'pages/faqs'
  get 'pages/about_us'
  get 'pages/our_team'
  get 'pages/author_portal'
  get 'pages/why'
  get 'pages/community_standards'
  get 'pages/what_we_do'
  get 'pages/why_model_works'
  get 'pages/printing_costs'
  get 'pages/klososky'
  get 'pages/rewilding'
  get 'pages/discipling'
  get 'pages/predicament'
  get 'pages/covenant'
  get 'pages/piatt'

  get 'authors', to: 'bios#browse', as: :browse_authors
  get 'users', to: 'users#show', as: :user_root
  get 'admin', to: 'admin/users#index', as: :admin_root
  root to: 'pages#welcome'
end

app/models/reward.rb
# == Schema Information
#
# Table name: rewards
#
#  id                        :integer          not null, primary key
#  campaign_id               :integer          not null
#  description               :string(100)      not null
#  long_description          :text
#  minimum_contribution      :decimal(, )      not null
#  physical_address_required :boolean          default(FALSE), not null
#  house_reward_id           :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  photo_id                  :integer
#

class Reward < ActiveRecord::Base
  belongs_to :house_reward
  belongs_to :campaign
  has_many :fulfillments, dependent: :restrict_with_error
  has_many :contributions, through: :fulfillments

  before_save :process_photo_file

  validates_presence_of :campaign_id, :description, :minimum_contribution
  validates_length_of :description, maximum: 100
  validates_uniqueness_of :description, scope: :campaign_id
  validates_numericality_of :minimum_contribution, greater_than: 0

  attr_accessor :photo_file

  scope :by_minimum_contribution, ->{order(:minimum_contribution)}
  scope :for_amount, ->(amount){where('minimum_contribution <= ?', amount)}

  def initialize(attributes = {})
    super
    apply_house_reward_attributes
  end

  def as_json(options = {})
    super options.merge(methods: [:working_description,
                                  :working_long_description])
  end

  def estimate_cost
    return unless house_reward.present?
    house_reward.estimate_cost(fulfillments.count)
  end

  def working_description
    house_reward ? house_reward.description : description
  end

  def working_physical_address_required
    house_reward ? house_reward.physical_address_required : physical_address_required
  end

  def working_long_description
    return long_description if long_description.present?
    return house_reward.long_description if house_reward.present?
  end

  def visible_to_owner?
    true
  end

  def visible_to_public?
    campaign.active?
  end

  private

  def apply_house_reward_attributes
    return unless house_reward
    self.description = house_reward.description
    self.physical_address_required = house_reward.physical_address_required
  end

  def process_photo_file
    return unless photo_file

    image = Image.find_or_create_from_file(photo_file, campaign.book.author)
    self.photo_id = image.id if image
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  respond_to :html, :json

  before_filter :authenticate_user!, except: :index
  before_filter :load_campaign, only: [:index, :new, :create]
  before_filter :load_reward, only: [:edit, :update, :destroy]

  def index
    @rewards = @campaign.rewards
    respond_with @rewards
  end

  def new
    @reward = @campaign.rewards.new
    authorize! :create, @reward
  end

  def create
    @reward = @campaign.rewards.new reward_params
    authorize! :create, @reward
    flash[:notice] = 'The reward was created successfully.' if @reward.save
    respond_with @reward, location: edit_campaign_path(@campaign)
  end

  def edit
    authorize! :update, @reward
  end

  def update
    authorize! :update, @reward
    @reward.update_attributes reward_params
    flash[:notice] = 'The reward was updated successfully.' if @reward.save
    respond_with @reward, location: edit_campaign_path(@campaign)
  end

  def destroy
    authorize! :destroy, @reward
    flash[:notice] = 'The reward was removed successfully.' if @reward.destroy
    redirect_to edit_campaign_path(@campaign)
  end

  private

  def load_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end

  def load_reward
    @reward = Reward.find(params[:id])
    @campaign = @reward.campaign
  end

  def reward_params
    params.require(:reward).permit(:description,
                                   :long_description,
                                   :photo_file,
                                   :minimum_contribution,
                                   :physical_address_required,
                                   :house_reward_id)
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
  def house_reward_options_for_select(selected)
    options_from_collection_for_select HouseReward.all, :id, :description, selected
  end
end

app/views/rewards/_form_fields.html.haml
.row
  .col-md-6
    .form-group{ class: form_group_class(@reward, :description) }
      =f.label :description, class: 'control-label'
      =f.text_field :description, class: 'form-control', autofocus: true
      =help_blocks(@reward, :description)
    .form-group{ class: form_group_class(@reward, :long_description) }
      =f.label :long_description, class: 'control-label'
      =f.text_area :long_description, class: 'form-control', rows: 3
      =help_blocks(@reward, :long_description)
    .form-group{ class: form_group_class(@reward, :minimum_contribution) }
      =f.label :minimum_contribution, class: 'control-label'
      =f.number_field :minimum_contribution, class: 'form-control', rows: 3, min: 1, step: 1
      =help_blocks(@reward, :minimum_contribution)
    .checkbox
      %label
        =f.check_box :physical_address_required
        Physical address required
  .col-md-6
    .form-group{ class: form_group_class(@reward, :photo_file) }
      =f.label :photo_file, class: 'control-label'
      =f.file_field :photo_file, class: 'form-control'
      =help_blocks(@reward, :photo_file)
    -if @reward.photo_id
      %img.img-rounded.img-responsive{ src: image_path(@reward.photo_id) }
.row
  .col-md-6
    =f.submit 'Save', class: 'btn btn-primary', title: 'Click here to save this reward.'
    =link_to 'Back', edit_campaign_path(@campaign), class: 'btn btn-default', title: 'Click here to cancel and return to the campaign edit form.'

app/views/rewards/_house_reward_form_fields.html.haml
.row
  .col-md-6
    .form-group{ class: form_group_class(@reward, :house_reward_id) }
      =f.label :house_reward_id, 'Reward', class: 'control-label'
      =f.select :house_reward_id, house_reward_options_for_select(@reward.house_reward_id), {}, class: 'form-control', autofocus: true
      =help_blocks(@reward, :house_reward_id)
    .form-group{ class: form_group_class(@reward, :long_description) }
      =f.label :long_description, class: 'control-label'
      =f.text_area :long_description, class: 'form-control', rows: 3
      =help_blocks(@reward, :long_description)
    .form-group{ class: form_group_class(@reward, :minimum_contribution) }
      =f.label :minimum_contribution, class: 'control-label'
      =f.number_field :minimum_contribution, class: 'form-control', rows: 3, min: 1, step: 1
      =help_blocks(@reward, :minimum_contribution)
  .col-md-6
    .form-group{ class: form_group_class(@reward, :photo_file) }
      =f.label :photo_file, class: 'control-label'
      =f.file_field :photo_file, class: 'form-control'
      =help_blocks(@reward, :photo_file)
    -if @reward.photo_id
      %img.img-rounded.img-responsive{ src: image_path(@reward.photo_id) }
.row
  .col-md-6
    =f.submit 'Save', class: 'btn btn-primary', title: 'Click here to save this reward.'
    =link_to 'Back', edit_campaign_path(@campaign), class: 'btn btn-default', title: 'Click here to cancel and return to the campaign edit form.'

app/views/rewards/_list.html.haml
%table#rewards-table.table.table-striped
  %tr
    %th Description
    %th Min. contribution
    %th &nbsp;
  -@campaign.rewards.by_minimum_contribution.each do |reward|
    %tr
      %td= reward.working_description
      %td= number_to_currency(reward.minimum_contribution, precision: 0)
      %td
        -if reward.contributions.any?
          &nbsp;
        -else
          .btn-group
            =link_to edit_reward_path(reward), class: 'btn btn-xs btn-info edit-button', title: 'Click here to edit this reward.' do
              %span.glyphicon.glyphicon-pencil{ 'arial-hidden' => true }
            =link_to reward_path(reward), method: :delete, class: 'btn btn-xs btn-danger delete-button', title: 'Click here to remove this reward.' do
              %span.glyphicon.glyphicon-remove{ 'arial-hidden' => true }
=link_to 'Add', new_campaign_reward_path(@campaign), class: 'btn btn-primary', title: 'Click here to add a reward for the campaign.'

app/views/rewards/edit.html.haml
=content_for :page_title do
  Edit reward

.container.container-default
  =form_for(@reward) do |f|
    -if @reward.house_reward_id
      =render 'house_reward_form_fields', f: f
    -else
      =render 'form_fields', f: f

app/views/rewards/new.html.haml
=content_for :page_title do
  New reward

.container.container-default
  .row
    .col-md-6
      #house-fulfilled
        %h2 Fulfilled by Crowdscribed
        %p
          The cost for fulfilling these rewards, including setup, printing, and
          shipping, will be subtracted from the money that is raised during the
          campaign. See our
          =link_to 'pricing sheet', '/docs/price_list.pdf', target: '_blank'
          for more details.
        =form_for([@campaign, @reward]) do |f|
          =render 'house_reward_form_fields', f: f
    .col-md-6
      #author-fulfilled
        %h2 Fulfilled by you
        %p
          You will be responsible for fulfilling these items yourself. You
          may use money raised during the campaign to pay for book orders,
          but you will be responsible for shipping and any other costs not
          associated with Crowdscribed.com.
        =form_for([@campaign, @reward]) do |f|
          =render 'form_fields', f: f