config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount ResqueWeb::Engine => '/resque_web'

  devise_for :administrators, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :subscribers, only: [:new, :create, :show]
  resources :inquiries, only: [:new, :create, :show]
  get '/unsubscribe/:token', to: 'users#unsubscribe',
                             as: :unsubscribe,
                             constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  get '/profile/edit', to: 'users#edit',
                       as: :edit_profile
  resources :users, only: [:show, :edit, :update, :index] do
    resources :bios, only: [:new, :index, :create]
  end
  resources :bios, only: [:show, :edit, :update, :index, :create, :new]
  resources :books, only: [:index, :show, :edit, :update, :new, :create] do
    resources :book_versions, path: 'versions', only: [:new, :create, :index]
    resources :campaigns, only: [:index, :new, :create]
    collection do
      get :browse
    end
  end
  resources :book_versions, only: [:edit, :update, :show]
  resources :images, only: :show
  resources :campaigns, only: [:show, :edit, :update, :destroy] do
    resources :contributions, only: [:new, :create]
    resources :rewards, only: [:index, :new, :create]
    member do
      get :terms
      patch :start
      patch :collect
      patch :cancel
      patch :prolong
    end
  end
  resources :contributions, only: [:edit, :update] do
    member do
      get :reward
      patch :set_reward
      get :payment
      patch :pay
    end
  end
  get '/contributions/:token', to: 'contributions#show',
                               as: :show_contribution,
                               constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  resources :payments, only: :create do
    collection do
      get :token
    end
  end
  resources :rewards, only: [:edit, :update, :destroy]
  resources :fulfillments, only: [:index] do
    member do
      patch :fulfill
    end
  end

  namespace :admin do
    resources :authors do
      resources :bios, only: [:new, :create]
      resources :books, only: [:index, :new, :create]
    end
    resources :bios, only: [:edit, :update]
    resources :books, only: [:edit, :destroy]
    resources :book_versions, only: :update
    resources :inquiries, only: [:index, :show] do
      member do
        patch :archive
      end
    end
    resources :users, only: [:index, :show]
    resources :bios, only: [:index, :show] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :book_versions, only: [:show, :index] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :campaigns, only: [:index, :show]
    resources :house_rewards
    resources :fulfillments, only: [:index] do
      member do
        patch :fulfill
      end
    end
    resources :payments, only: [:index, :show] do
      member do
        patch :refresh
        patch :refund
      end
    end
    resources :subscribers, only: [:index]
  end

  get 'pages/welcome'
  get 'pages/package_pricing'
  get 'pages/book_prices'
  get 'pages/a_la_carte_pricing'
  get 'pages/traditional_vs_pod'
  get 'pages/faqs'
  get 'pages/about_us'
  get 'pages/our_team'
  get 'pages/author_portal'
  get 'pages/why'
  get 'pages/community_standards'
  get 'pages/what_we_do'
  get 'pages/why_model_works'
  get 'pages/printing_costs'
  get 'pages/klososky'
  get 'pages/rewilding'
  get 'pages/discipling'
  get 'pages/predicament'
  get 'pages/covenant'
  get 'pages/piatt'

  get 'authors', to: 'bios#browse', as: :browse_authors
  get 'users', to: 'users#show', as: :user_root
  get 'admin', to: 'admin/users#index', as: :admin_root
  root to: 'pages#welcome'
end

app/views/shared/_admin_navigation.html.haml
%nav#main-menu.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to image_tag(asset_path('crowdscribed_logo.png')), root_path
    #navbar.navbar-collapse.collapse
      =render_navigation context: :admin, renderer: :bootstrap_navigation_renderer, expand_all: true

app/views/shared/_approval_buttons.html.haml
-unless resource.approved?
  =button_to 'Approve', send(approve_path(resource)), method: :patch, class: 'btn btn-success btn-block', title: "Click here to approve the #{resource.class.name.downcase}."
-unless resource.rejected?
  =link_to 'Reject', send(reject_path(resource)), class: 'btn btn-danger btn-block', title: "Click here to reject the #{resource.class.name.downcase}."

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  =render 'shared/top_bar'
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to image_tag(asset_path('crowdscribed_logo.png')), root_path
    #navbar.collapse.navbar-collapse
      #main-menu
        =render_navigation renderer: :bootstrap_navigation_renderer, expand_all: true

app/views/shared/_payment_fees.html.haml
%h2 What fees are deducted from the amount my campaign raises?
%p
  Crowdscribed never deducts fees from what you raise just for raising
  it. We make our money helping you make and sell your book! However,
  our third party services providers do, so keep this in mind. Each
  credit card contribution has a deduction of 2.9% of the amount, plus
  30 cents per transaction. This is also similar to the feee charged by
  Paypal if your supporter used that.

%p
  So if you raised $1,000 from ten $100 donations:
  %blockquote
    $1000 - (($1000 x 2.9%) + (10 x $.30)) = $1000 - ($29 + $3) = $967

%p
  From one hundred $10 donations:
  %blockquote
    $1000 - (($1000 x 2.9%) + (100 x $.30)) = $1000 - ($29 + $30) = $941

%p
  These are estimates and may vary depending on what the third-party
  payment processors charge. And as always, you cannot “cash out” what
  you raised; all remaining funds must be used toward
  Crowdscribed-provided book production services and/or copies of your
  book (and related shipping and taxes).

app/views/shared/_payment_fees_modal.html.haml
%button#fee-notes-button.btn.btn-sm.btn-default{ data: {toggle: 'modal', target: '#fee-notes' } }
  Note about fees
#fee-notes.modal.fade{ role: 'dialog' }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ 'data-dismiss' => 'modal' }
          &times;
        Note about fees
      .modal-body
        =render 'shared/payment_fees'
      .modal-footer
        %button.btn.btn-primary{ 'data-dismiss' => 'modal' } OK

app/views/shared/_progress_meter.html.haml
%svg{ width: width, height: height}
  %rect{ x: 0, y: 0, width: width, height: height, style: 'fill:#FFF;stroke-width:4;stroke:#00ADDE' }
  %rect{ x: 0, y: height * (1 - progress), width: width, height: height * progress, style: 'fill:#00ADDE;stroke-width:4;stroke:#00ADDE' }
  -if progress < 0.4
    -text_y = height / 2
    -text_color = '#00ADDE'
  -else
    -text_y = height * (1 - (progress/2.0))
    -text_color = '#FFF'
  %text{ x: width / 6, y: text_y, fill: text_color, font: { size: 30, family: 'Quicksand', weight: 'bold' } }
    =number_to_percentage (100 * progress), precision: 0

app/views/shared/_top_bar.html.haml
#top-bar
  .container
    -unless AppSetting.sign_in_disabled?
      .row
        .col-md-7.col-md-offset-5.text-right
          -if user_signed_in?
            =link_to current_user.full_name, user_path(current_user)
            -if !AppSetting.sign_in_disabled?
              |
              =link_to 'Sign out', destroy_user_session_path, method: :delete, title: 'Click here to end your session.'
          -else
            =form_tag session_path(:user), class: 'form-inline' do
              .form-group
                =label_tag 'user[email]', 'Email', class: 'sr-only'
                =text_field_tag 'user[email]', nil, class: 'form-control', placeholder: 'Email'
              .form-group
                =label_tag 'user[password]', 'Password', class: 'sr-only'
                =password_field_tag 'user[password]', nil, class: 'form-control', placeholder: 'Password'
              .checkbox
                =label_tag 'user[remember_me]' do
                  =check_box_tag 'user[remember_me]'
                  Remember me
              .form-group
                =submit_tag 'Sign in', class: 'btn btn-default'

app/views/shared/_wysiwyg.html.haml
=content_for :header do
  =javascript_include_tag 'wysiwyg'
  =stylesheet_link_tag 'wysiwyg'
=content_for :after_footer do
  :coffee
    $(->
      $('.wysiwyg').froalaEditor
        key: '#{ENV['FROALA_ACTIVATION_KEY']}')