config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount ResqueWeb::Engine => '/resque_web'

  devise_for :administrators, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  resources :subscribers, only: [:new, :create, :show]
  resources :inquiries, only: [:new, :create, :show]
  get '/unsubscribe/:token', to: 'users#unsubscribe',
                             as: :unsubscribe,
                             constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  get '/profile/edit', to: 'users#edit',
                       as: :edit_profile
  resources :users, only: [:show, :edit, :update, :index] do
    resources :bios, only: [:new, :index, :create]
  end
  resources :bios, only: [:show, :edit, :update, :index, :create, :new]
  resources :books, only: [:index, :show, :edit, :update, :new, :create] do
    resources :book_versions, path: 'versions', only: [:new, :create, :index]
    resources :campaigns, only: [:index, :new, :create]
    collection do
      get :browse
    end
  end
  resources :book_versions, only: [:edit, :update, :show]
  resources :images, only: :show
  resources :campaigns, only: [:show, :edit, :update, :destroy] do
    resources :contributions, only: [:new, :create]
    resources :rewards, only: [:index, :new, :create]
    member do
      get :terms
      patch :start
      patch :collect
      patch :cancel
      patch :prolong
    end
  end
  resources :contributions, only: [:edit, :update] do
    member do
      get :reward
      patch :set_reward
      get :payment
      patch :pay
    end
  end
  get '/contributions/:token', to: 'contributions#show',
                               as: :show_contribution,
                               constraints: { token: /[a-z0-9]{8}(?:-[a-z0-9]{4}){3}-[a-z0-9]{12}/i }
  resources :payments, only: :create do
    collection do
      get :token
    end
  end
  resources :rewards, only: [:edit, :update, :destroy]
  resources :fulfillments, only: [:index] do
    member do
      patch :fulfill
    end
  end

  namespace :admin do
    resources :authors do
      resources :bios, only: [:new, :create]
      resources :books, only: [:index, :new, :create]
    end
    resources :bios, only: [:edit, :update]
    resources :books, only: [:edit, :destroy]
    resources :book_versions, only: :update
    resources :inquiries, only: [:index, :show] do
      member do
        patch :archive
      end
    end
    resources :users, only: [:index, :show]
    resources :bios, only: [:index, :show] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :book_versions, only: [:show, :index] do
      member do
        patch :approve
        get :prereject
        patch :reject
      end
    end
    resources :campaigns, only: [:index, :show]
    resources :house_rewards
    resources :fulfillments, only: [:index] do
      member do
        patch :fulfill
      end
    end
    resources :payments, only: [:index, :show] do
      member do
        patch :refresh
        patch :refund
      end
    end
    resources :subscribers, only: [:index]
  end

  get 'pages/welcome'
  get 'pages/package_pricing'
  get 'pages/book_prices'
  get 'pages/a_la_carte_pricing'
  get 'pages/traditional_vs_pod'
  get 'pages/faqs'
  get 'pages/about_us'
  get 'pages/our_team'
  get 'pages/author_portal'
  get 'pages/why'
  get 'pages/community_standards'
  get 'pages/what_we_do'
  get 'pages/why_model_works'
  get 'pages/printing_costs'
  get 'pages/klososky'
  get 'pages/rewilding'
  get 'pages/discipling'
  get 'pages/predicament'
  get 'pages/covenant'
  get 'pages/piatt'

  get 'authors', to: 'bios#browse', as: :browse_authors
  get 'users', to: 'users#show', as: :user_root
  get 'admin', to: 'admin/users#index', as: :admin_root
  root to: 'pages#welcome'
end

app/models/book_version.rb
# == Schema Information
#
# Table name: book_versions
#
#  id                :integer          not null, primary key
#  book_id           :integer          not null
#  title             :string(255)      not null
#  short_description :string(1000)     not null
#  long_description  :text
#  cover_image_id    :integer
#  sample_id         :integer
#  status            :string           default("pending"), not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class BookVersion < ActiveRecord::Base
  include Approvable

  belongs_to :book
  has_and_belongs_to_many :genres

  before_save :process_cover_image_file, :process_sample_file

  validates_presence_of :book, :title, :short_description
  validates :title, length: { maximum: 255 }
  validates :short_description, length: { maximum: 1000 }
  validate :sample_file, :must_be_pdf
  validate :cover_image_file, :must_be_image
  validate :genres, :cannot_have_more_than_3

  attr_accessor :cover_image_file, :sample_file
  delegate :author, :active_campaign, to: :book

  def long_or_short_description
    long_description.present? ? long_description : short_description
  end

  def new_copy
    result = book.versions.new
    [:title,
     :short_description,
     :long_description,
     :cover_image_id,
     :status,
     :comments,
     :sample_id].each do |field|
       result.send("#{field}=", self.send(field))
     end
     genres.each{|g| result.genres << g}
     result
  end

  def visible_to_owner?
    !rejected?
  end

  def visible_to_public?
    approved?
  end

  private

  def cannot_have_more_than_3
    errors.add(:genres, 'cannot have more than three selections') if genres.to_a.count > 3
  end

  def pdf?(file)
    file.content_type == 'application/pdf'
  end

  def must_be_pdf
    if sample_file.present? && !pdf?(sample_file)
      errors.add(:sample_file, "must be a PDF")
    end
  end

  IMAGE_PATTERN = /\.(?:jpe?g|png|gif)$/

  def image?(file)
    (file.respond_to?(:content_type) && file.content_type.start_with?("image")) ||
      (file.respond_to?(:extname) && !!(IMAGE_PATTERN =~ file.extname))
  end

  def must_be_image
    if cover_image_file.present? && !image?(cover_image_file)
      errors.add(:cover_image_file, "must be an image")
    end
  end

  def process_cover_image_file
    return unless cover_image_file

    image = Image.find_or_create_from_file(cover_image_file, author)
    self.cover_image_id = image.id if image
  end

  def process_sample_file
    return unless sample_file

    image = Image.find_or_create_from_file(sample_file, author)
    self.sample_id = image.id if image
  end

  def current_version
    book.approved_version
  end
end

app/controllers/admin/book_versions_controller.rb
class Admin::BookVersionsController < ApplicationController
  before_filter :authenticate_administrator!
  before_filter :load_book_version, only: [:show, :update, :approve, :prereject, :reject]
  respond_to :html
  layout 'admin'

  def index
    @book_versions = book_versions_by_status.paginate(page: params[:page])
  end

  def show
    authorize! :show, @book_version
  end

  def update
    @book_version.update_attributes book_version_params.except(:genres)
    update_genres
    flash[:notice] = 'The book was updated successfully.' if @book_version.save
    respond_with @book_version, location: admin_author_books_path(@book_version.book.author_id)
  end

  def approve
    authorize! :approve, @book_version
    if @book_version.approve!
      BookMailer.approval(@book_version).deliver_now unless @book_version.author.unsubscribed?
      redirect_to admin_book_versions_path, notice: 'The book has been approved successfully.'
    else
      render :show
    end
  end

  def prereject
  end

  def reject
    authorize! :reject, @book_version
    @book_version.update_attributes rejection_params
    if @book_version.reject!
      BookMailer.rejection(@book_version).deliver_now unless @book_version.author.unsubscribed?
      redirect_to admin_book_versions_path, notice: 'The book has been rejected successfully.'
    else
      render :show
    end
  end

  private

  def book_versions_by_status
    BookVersion.where(status: params[:status] || :pending)
  end

  def load_book_version
    @book_version = BookVersion.find(params[:id])
  end

  def book_version_params
    params.require(:book_version).permit(:title,
                                         :short_description,
                                         :long_description,
                                         :cover_image_file,
                                         :sample_file,
                                         genres: [])
  end

  def rejection_params
    params.require(:book_version).permit(:comments)
  end

  def set_diff(current, target)
    to_add = target - current
    to_remove = current - target
    [to_add, to_remove]
  end

  def genres_from_params
    genre_ids = params[:book_version][:genres]
    if genre_ids
      Genre.find(genre_ids)
    else
      []
    end
  end

  def update_genres
    to_add, to_remove = set_diff(@book_version.genres,
                                 genres_from_params)
    to_add.each{|g| @book_version.genres << g}
    to_remove.each{|g| @book_version.genres.delete g}
  end
end

app/controllers/book_versions_controller.rb
class BookVersionsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_filter :load_book_version, only: [:show, :edit, :update]
  before_filter :load_book, only: [:index, :new, :create]
  respond_to :html

  def index
    authorize! :version, @book
  end

  def show
    authorize! :show, @book_version
  end

  def new
    if @book.pending_version
      redirect_to edit_book_version_path(@book.pending_version)
      return
    end
    @book_version = @book.most_recent_version.new_copy
    authorize! :create, @book_version
  end

  def create
    if @book.pending_version
      redirect_to edit_book_version_path(@book.pending_version)
      return
    end

    @book_version = @book.versions.new(book_version_params)
    authorize! :create, @book_version
    genres_from_params.each{|g| @book_version.genres << g}
    if @book_version.save
      flash[:notice] = 'The book was updated successfully.'
      AdminMailer.book_edit_submission(@book_version).deliver_now
    end
    respond_with @book_version
  end

  def edit
    with_permission do
      unless @book_version.pending?
        redirect_to new_book_book_version_path(@book_version.book_id)
        return
      end
    end
  end

  def update
    with_permission do
      authorize! :update, @book_version
      @book_version.update_attributes book_version_params
      update_genres
      flash[:notice] = "The book was updated successfully." if @book_version.save
      respond_with @book_version, location: book_path(@book_version.book)
    end
  end

  private

  def book_author_id
    @book.try(:author_id) || @book_version.book.author_id
  end

  def book_version_params
    params.require(:book_version).permit(:title,
                                         :short_description,
                                         :long_description,
                                         :cover_image_file,
                                         :cover_image_id,
                                         :sample_file,
                                         :sample_id)
  end

  def genres_from_params
    genre_ids = params.require(:book_version).permit(genres: [])[:genres]
    if genre_ids
      Genre.find(genre_ids)
    else
      []
    end
  end

  def load_book
    @book = Book.find(params[:book_id])
  end

  def load_book_version
    @book_version = BookVersion.find(params[:id])
  end

  def set_diff(current, target)
    to_add = target - current
    to_remove = current - target
    [to_add, to_remove]
  end

  def update_genres
    to_add, to_remove = set_diff(@book_version.genres,
                                 genres_from_params)
    to_add.each{|g| @book_version.genres << g}
    to_remove.each{|g| @book_version.genres.delete g}
  end

  def with_permission
    unless user_signed_in?
      # Not a user, they can't edit it
      redirect_to root_path, notice: "We were not able to find the resource you requested."
      return
    end

    unless current_user.id == @book_version.book.author_id
      # Not the owner, they can't edit it
      redirect_to user_root_path, notice: "We were not able to find the resource you requested."
      return
    end

    unless @book_version.pending?
      # they can't edit it, but they can create a new version
      redirect_to new_book_book_version_path(@book_version.book)
      return
    end

    yield if block_given?
  end
end

app/helpers/book_versions_helper.rb
module BookVersionsHelper
  def dynamic_edit_path(book_version)
    if book_version.book.pending_version
      edit_book_version_path(book_version.book.pending_version)
    else
      new_book_book_version_path(book_version.book)
    end
  end
end

app/views/book_versions/_details.html.haml
.row
  .col-md-4
    -if book_version.cover_image_id
      %img{ src: image_path(book_version.cover_image_id), class: 'img-rounded img-responsive' }
    -if book_version.sample_id
      %p.sample-container
        %a.sample-link{ href: image_path(book_version.sample_id), target: '_blank' } Download a sample
    -if book_version.genres.any?
      %ul.tag-list
        -book_version.genres.each do |genre|
          %li=genre.name
  .col-md-8
    .row
      .col-sm-12
        -if book_version.approved?
          =book_version.long_or_short_description.html_safe
        -else
          %p=book_version.long_or_short_description
    -if can?(:update, book_version.book) && book_version.book.campaigns.none? && book_version.approved?
      .row
        .col-sm-12
          .button-panel
            =link_to 'create a funding campaign', book_campaigns_path(book_version.book_id), :class => 'btn btn-lg btn-success', :title => 'Click here to create a crowdfunding campaign for this title.'
    -if book_version.active_campaign.present?
      .row
        .col-sm-6
          %h3 Contribute to the campaign!
          =render 'campaigns/progress_table', campaign: book_version.active_campaign
          =link_to 'Contribute!', new_campaign_contribution_path(book_version.active_campaign), :class => 'btn btn-lg btn-success', :title => 'Click here to contribute to the campaign to make this book a reality!'
        .col-sm-2.col-sm-offset-2
          =render_progress_meter book_version.active_campaign.current_progress

app/views/book_versions/_form_fields.html.haml
= render 'shared/wysiwyg'
.row
  .col-md-6
    .form-group{ :class => form_group_class(book_resource, :title) }
      =f.label :title, class: 'control-label'
      =f.text_field :title, class: 'form-control', autofocus: true
      =help_blocks book_resource, :title
    .form-group{ :class => form_group_class(book_resource, :short_description) }
      =f.label :short_description, class: 'control-label'
      =f.text_area :short_description, class: 'form-control wysiwyg', rows: 5
      =help_blocks book_resource, :short_description
    .form-group{ :class => form_group_class(book_resource, :long_description) }
      =f.label :long_description, class: 'control-label'
      =f.text_area :long_description, class: 'form-control wysiwyg', rows: 10
      =help_blocks book_resource, :long_description
    .form-group
      -if book_resource.cover_image_id
        .row
          .col-sm-6
            %img{ src: image_path(book_resource.cover_image_id), class: 'img img-responsive img-rounded pull-left' }
            =f.hidden_field :cover_image_id
          .col-sm-6
            =f.label :cover_image_file, class: 'control-label'
            =f.file_field :cover_image_file, class: 'form-control'
            =help_blocks book_resource, :cover_image_file
            %p.instructional
              The cover image file should be a JPEG (JPG), PNG, or GIF. It will automatically
              be reduced to fit 1024 x 1024 pixels on upload if either the height or the
              width is greater than 1024. Please do not upload files that are substantially 
              larger than that.
      -else
        =f.label :cover_image_file, class: 'control-label'
        =f.file_field :cover_image_file, class: 'form-control'
        =help_blocks book_resource, :cover_image_file
        %p.instructional
          The cover image file should be a JPEG (JPG), PNG, or GIF. It will automatically
          be reduced to fit 1024 x 1024 pixels on upload if either the height or the
          width is greater than 1024. Please do not upload files that are substantially 
          larger than that.
    .form-group{ :class => form_group_class(book_resource, :sample_file) }
      =f.label :sample_file, class: 'control-label'
      -if book_resource.sample_id
        .row
          .col-sm-3
            =link_to 'Download existing', image_path(book_resource.sample_id), class: 'sample-link'
            =f.hidden_field :sample_id
          .col-sm-9
            =f.file_field :sample_file, class: 'form-control'
            =help_blocks book_resource, :sample_file
            %p.instructional
              Sample files should be in PDF format. The sample should include enough of the
              book content to engage the reader without giving away the entire story.
      -else
        =f.file_field :sample_file, class: 'form-control'
        =help_blocks book_resource, :sample_file
        %p.instructional
          Sample files should be in PDF format. The sample should include enough of the
          book content to engage the reader without giving away the entire story.
  .col-md-6
    .form-group{ :class => form_group_class(book_resource, :genres) }
      =f.label :genres, 'Genres', class: 'control-label'
      .instructional Select up to 3 genres
      .row.genre-list
        -genre_groups(2).each do |genre_group|
          .col-sm-6
            -genre_group.each do |genre|
              .checkbox
                =label_tag "genres_#{genre.id}" do
                  =check_box_tag "#{book_resource.model_name.to_s.underscore}[genres][]", genre.id, book_resource.genres.map(&:id).include?(genre.id), id: "genres_#{genre.id}"
                  =genre.name
      =help_blocks book_resource, :genres
.row
  .col-md-6
    .form-group
      =f.submit submit_caption, class: 'btn btn-primary', title: submit_tool_tip
      =link_to 'Back', back_path, class: 'btn btn-default', title: back_tool_tip

app/views/book_versions/_rejection_notice.html.haml
.panel.panel-danger
  .panel-heading Rejected
  .panel-body
    %p
      This book has been rejected by the administrator because it does
      not conform to our
      #{h link_to 'community standards', pages_community_standards_path, target: '_blank' }.
    -if @book_version.comments.present?
      %p= @book_version.comments

app/views/book_versions/edit.html.haml
=content_for :page_title do
  Edit book

.container.container-default
  -if @book_version.rejected?
    =render 'rejection_notice', book_version: @book_version
  =form_for(@book_version) do |f|
    =render 'form_fields', f: f, book_resource: @book_version, submit_caption: 'Submit', submit_tool_tip: 'Click here to submit this book.', back_path: books_path, back_tool_tip: 'Click here to return to the list of books.'

app/views/book_versions/index.html.haml
=content_for :page_title do
  Versions

app/views/book_versions/new.html.haml
=content_for :page_title do
  Edit book

.container.container-default
  -if @book_version.rejected?
    =render 'rejection_notice', book_version: @book_version
  =form_for([@book, @book_version]) do |f|
    =render 'form_fields', f: f, book_resource: @book_version, submit_caption: 'Submit', submit_tool_tip: 'Click here to submit this book.', back_path: books_path, back_tool_tip: 'Click here to return to the list of books.'

app/views/book_versions/show.html.haml
=content_for :page_title do
  Book

.container.container-default
  .row
    .col-md-12
      -if can?(:update, @book_version) && @book_version.pending?
        .alert.alert-info
          This book is under review. We will review it as soon as we can.
      %h1#book-title= @book_version.title
      -if @book_version.author.active_bio.present?
        %h2= link_to @book_version.author.full_name, bio_path(@book_version.author.active_bio)
  =render 'details', book_version: @book_version
  -if can? :update, @book_version.book
    .row
      .col-md-3
        =link_to 'Edit', dynamic_edit_path(@book_version), class: 'btn btn-default'